[green_agent]
endpoint = "http://127.0.0.1:9009"
cmd = "python evaluator/src/server.py --host 127.0.0.1 --port 9009"

[[participants]]
role = "agent"
endpoint = "http://127.0.0.1:9019"
cmd = "python agent/src/server.py --host 127.0.0.1 --port 9019"

[config]
domain = "airline"
num_tasks = 4
